steps:
  - #Step 0 login
  - name: Login to GCR
    env:
        PROJECT_ID: noted-palisade-385613 #create env called PROJECT_ID consisted of our actual GCP Project ID
    uses: google-github-actions/setup-gcloud@v0.3.0 #checkouts GCR repo, so this workflow can access it
    with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }} #parse the value of repository secret called SERVICE_ACCOUNT_KEY that we have created earlier
        project_id: noted-palisade-385613 #parse the value of env called PROJECT_ID
        export_default_credentials: true
  # Step 1: Build the Docker image for the 'app' service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/noted-palisade-385613/app', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/noted-palisade-385613/app']

  # Step 3: Deploy the services using Docker Compose
  - name: 'eu.gcr.io/cloud-builders/docker-compose'
    args: ['-f', 'docker-compose.yml', 'up', '-d']

# Timeout and logs configuration (optional)
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
